### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by dsebastien** [mentos1386/nest-morgan#4]
Hello,

Would it be possible to add a way to customize how the message is logged?
I'd like to use a custom `Logger` instead of `console.error` for the messages.

Thanks for the library!

**Comment by mentos1386** [comment]
Arguments used when doing `@UseInterceptors(MorganInterceptor())` are the same as [normal morgan arguments](https://github.com/expressjs/morgan#morganformat-options). So you can use all the available morgan options.

You can see the types for `MoeganInterceptor()` here https://github.com/mentos1386/nest-morgan/blob/master/lib/morgan.interceptor.mixin.ts#L7.

**Comment by dsebastien** [comment]
Ok I see, so I suppose that the stream option will do with a function to log?

Thanks!

**Comment by mentos1386** [comment]
Closed due to inactivity.
